// 引入 ShareUtil.js 中的 NativeModule
import ShareUtil from './src/ShareUtil';

const SHARE_MEDIA = {
    SMS: "SMS",
    EMAIL: "EMAIL",
    SINA: "SINA",
    QZONE: "QZONE",
    QQ: "QQ",
    WEIXIN: "WEIXIN",
    WEIXIN_CIRCLE: "WEIXIN_CIRCLE",
    WEIXIN_FAVORITE: "WEIXIN_FAVORITE",
    WXWORK: "WXWORK",
    DOUBAN: "DOUBAN",
    FACEBOOK: "FACEBOOK",
    FACEBOOK_MESSAGER: "FACEBOOK_MESSAGER",
    TWITTER: "TWITTER",
    YIXIN: "YIXIN",
    YIXIN_CIRCLE: "YIXIN_CIRCLE",
    INSTAGRAM: "INSTAGRAM",
    PINTEREST: "PINTEREST",
    EVERNOTE: "EVERNOTE",
    POCKET: "POCKET",
    LINKEDIN: "LINKEDIN",
    FOURSQUARE: "FOURSQUARE",
    YNOTE: "YNOTE",
    WHATSAPP: "WHATSAPP",
    LINE: "LINE",
    FLICKR: "FLICKR",
    TUMBLR: "TUMBLR",
    ALIPAY: "ALIPAY",
    KAKAO: "KAKAO",
    BYTEDANCE: "BYTEDANCE",
    BYTEDANCE_PUBLISH: "BYTEDANCE_PUBLISH",
    BYTEDANCE_FRIENDS: "BYTEDANCE_FRIENDS",
    DROPBOX: "DROPBOX",
    VKONTAKTE: "VKONTAKTE",
    DINGTALK: "DINGTALK",
    HONOR: "HONOR",
    MORE: "MORE"
};


// 导出 ShareUtil 以及其他可能的模块
export { ShareUtil, SHARE_MEDIA };
